---
apiVersion: v1
kind: Namespace
metadata:
  name: hkhr-evaluation
  labels:
    name: hkhr-evaluation
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: hkhr-evaluation-staging
  labels:
    name: hkhr-evaluation-staging
    environment: staging